name: Hello
on: push

jobs:
  exec:
    name: Hello-World
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello, world! ⚡"
  
  curl:
    name: Fetch Todos
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        run: curl https://jsonplaceholder.typicode.com/todos
